version: '3.0'

services:
  algorand-node:
    build: 
      context: ./algorand-node
      args:
        repo: algorand/go-algorand
        ref: rel/stable
        future_protocol: 'true'
        create_sandnet: 'true'
        dev_mode: 'true'
    ports:
      - 4001:4001
      - 4002:4002
    environment:
      ALGOD_TOKEN: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
      KMD_TOKEN: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
      ENABLE_DEVELOPER_API: 'true'
      ARCHIVAL: 'true'
      NETWORK: 'sandnet' # If you are changing to a public network ensure to set a bind-mount for /node below
    # Uncomment for persistent storage in ./node
    #volumes:
    #  - ./volumes/node:/node

  algorand-indexer:
    build: 
      context: ./algorand-indexer
      args:
        repo: algorand/indexer
        ref: master
    ports: 
      - 8980:8980
    environment:
      POSTGRES_HOST: indexer-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: algorand
      POSTGRES_PASSWORD: algorand
      POSTGRES_DB: indexer
      ALGOD_HOST: algorand-node
      ALGOD_PORT: 4001
      ALGOD_TOKEN: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
      LOG_LEVEL: info
    depends_on:
      - indexer-db
      - algorand-node
    restart: on-failure

  indexer-db:
    image: "postgres:14.2-bullseye"
    expose:
      - 5432
    environment:
      POSTGRES_USER: algorand
      POSTGRES_PASSWORD: algorand
      POSTGRES_DB: indexer

  # Uncomment to enable automatic https on DOMAIN
  #caddy:
  #  image: caddy:2-alpine
  #  ports:
  #    - 80:80
  #    - 443:443
  #  environment:
  #    DOMAIN: example.com
  #  volumes:
  #    - ./Caddyfile:/etc/caddy/Caddyfile
