# An example configuration of a mainnet node
version: '3.0'

services:
  algorand-node:
    build: 
      context: ./algorand-node
      args:
        repo: algorand/go-algorand
        ref: rel/stable
        create_sandnet: false
    ports:
      - 4001:4001
      - 4002:4002
    environment:
      # BE SURE TO CHANGE TOKENS IF API IS PUBLIC
      ALGOD_TOKEN: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
      KMD_TOKEN: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
      ENABLE_DEVELOPER_API: true
      ARCHIVAL: false
      NETWORK: 'mainnet'
    volumes:
      - ./node:/node
    restart: unless-stopped
