# Example configuration of a public mainnet node with HTTPS
version: '3.0'

services:
  algorand-node:
    build: 
      context: ./algorand-node
      args:
        repo: algorand/go-algorand
        ref: rel/stable
        create_sandnet: false
    expose:
      - 4001
      - 4002
    environment:
      # BE SURE TO CHANGE TOKENS IF API IS PUBLIC
      ALGOD_TOKEN: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
      KMD_TOKEN: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
      NETWORK: 'mainnet'
    volumes:
      - ./node:/node
    restart: unless-stopped
  
  caddy:
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN: example.com
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile