# Example configuration of a public mainnet node with HTTPS
version: '3.0'

services:
  algorand-node:
    build: 
      context: ./algorand-node
      args:
        repo: algorand/go-algorand
        ref: rel/stable
        create_sandnet: 'false'
    expose:
      - 4001
      - 4002
    environment:
      # BE SURE TO CHANGE TOKENS IF API IS PUBLIC
      ALGOD_TOKEN: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
      KMD_TOKEN: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
      ENABLE_DEVELOPER_API: 'true'
      ARCHIVAL: 'true'
      NETWORK: 'mainnet'
    volumes:
      - ./volumes/node:/node
    restart: unless-stopped

  algorand-indexer:
    build: 
      context: ./algorand-indexer
      args:
        repo: algorand/indexer
        ref: master
    expose: 
      - 8980
    environment:
      POSTGRES_HOST: indexer-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: algorand
      POSTGRES_PASSWORD: algorand
      POSTGRES_DB: indexer
      ALGOD_HOST: algorand-node
      ALGOD_PORT: 4001
      ALGOD_TOKEN: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
      LOG_LEVEL: info
    depends_on:
      - indexer-db
      - algorand-node
    restart: on-failure
    volumes:
      - ./volumes/indexer:/data

  indexer-db:
    image: "postgres:14.2-bullseye"
    expose:
      - 5432
    environment:
      POSTGRES_USER: algorand
      POSTGRES_PASSWORD: algorand
      POSTGRES_DB: indexer  

  caddy:
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN: example.com
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile